name: ClassicPress Directory Coding Standard checks.

on: [pull_request, push]

jobs:
  phpcs:
      name: CPCS
      runs-on: ubuntu-latest
      # Add this block here to force Node 24 across the whole job
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        
      steps:
        - uses: actions/checkout@v6

        - name: CPCS get rules
          run: |
            wget https://raw.githubusercontent.com/ClassicPress/ClassicPress-Coding-Standards/main/phpcs.xml
            sed -i '/^\t.*/a\
              <file>.</file>
              ' phpcs.xml
            sed -i '/MY_DOMAIN/ s//post-visit-tally/' phpcs.xml

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            # PHP 7.4 is the standard baseline for CP compatibility
            php-version: '7.4'
            # We must include WPCS because CPCS inherits from it
            tools: phpcs, wp-coding-standards/wpcs

        - name: CPCS checks
          run: phpcs --standard=phpcs.xml .